# Generated by Django 3.2.8 on 2021-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, unique=True)),
                ('Color', models.CharField(max_length=120)),
                ('Price', models.PositiveIntegerField(default=0)),
                ('Copies', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
