# Generated by Django 3.2.8 on 2021-11-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('dispatched', 'dispatched')], default='order_placed', max_length=120)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.phone')),
            ],
        ),
    ]
